### ISSUE TITLE
Feature request: Remove buttons for stickers, super reactions and avatar nitro frames

### ISSUE THREAD

**Issue by nixRidge** [CroissantDuNord/discord-adblock#2]
Could it be possible to remove the "Stickers" button, "Stickers" category in the emoji picker, "Add super reaction" buttons and the seasonal frames people can add to their avatars with Nitro?

I know I'm asking a lot, just throwing them all in here in case you can add blocking rules for any or even all of these. Thanks a bunch! Love this plugin.

Edit: It would also be great if the entire "Payment Settings" section could be removed from the settings page too, but just like everything else I mentioned, these are just minor nitpicks :)

Edit 2: Here's the custom CSS I use if someone wants to go further and remove the stickers button, and other annoyances for anyone like me, who are stuck in the past and wish we were still using IRC:

```css
/* Remove Sticker Tab */
#sticker-picker-tab {
  display: none;
}

/* Remove Sticker Button */
div.expression-picker-chat-input-button:nth-child(4) {
  display: none;
}

/* Remove Guilds and create new DM button, pad friends button */
nav.wrapper_a7e7a8 {
  display: none;
}
h2.privateChannelsHeaderContainer_ddcec6 {
  display: none;
}
li.channel_c21703:nth-of-type(1) {
  padding: 0 0 5% 0;
}

/* Remove Active Now Sidebar*/
div.nowPlayingColumn_f5023f {
  display: none;
}

/* Remove DM list status messages */
div.activity_a8c37a {
  display: none;
}

/* Remove friends list status messages */
.subtext__1a662 {
  display: none;
}

/* Hide search bar in the left sidebar */
div.searchBar_e4ea2a {
 display: none;
}

/* Remove avatar decorations */
svg.avatarDecoration_ae35e3 {
  display: none;
}

/* Remove profile decorations */
div.profileEffects_fd33f6 {
  display: none;
}
```

**_Updated 28th of October, 2023_**
