### ISSUE TITLE
Lottiefiles Gift button

### ISSUE THREAD

**Issue by EnderGamingz** [CroissantDuNord/discord-adblock#45]
The new chat icons are animated with lottiefiles and the gift button path has changed.

Hiding it is now possible by selecting the initial path the icon has:
```css
div[class^=buttons_] > button:has(path[d=" M-7,10 C-8.104999542236328,10 -9,9.104999542236328 -9,8 C-9,8 -9,2.5 -9,2.5 C-9,2.2239999771118164 -8.776000022888184,2 -8.5,2 C-8.5,2 -1.5,2 -1.5,2 C-1.2239999771118164,2 -1,2.2239999771118164 -1,2.5 C-1,2.5 -1,9.5 -1,9.5 C-1,9.776000022888184 -1.2239999771118164,10 -1.5,10 C-1.5,10 -7,10 -7,10z M1,9.5 C1,9.776000022888184 1.2239999771118164,10 1.5,10 C1.5,10 7,10 7,10 C8.104999542236328,10 9,9.104999542236328 9,8 C9,8 9,2.5 9,2.5 C9,2.2239999771118164 8.776000022888184,2 8.5,2 C8.5,2 1.5,2 1.5,2 C1.2239999771118164,2 1,2.2239999771118164 1,2.5 C1,2.5 1,9.5 1,9.5z"]) {
  display: none;
}
```

it would also be possible to hide it by selecting the label but this might break on different languages:
```css
div[class^=buttons_] > button[aria-label="Send a gift"] {
  display: none;
}
```
