### ISSUE TITLE
[Extras List] Nameplates not hidden despite the CSS being there in extras list

### ISSUE THREAD

**Issue by caffeinepx** [CroissantDuNord/discord-adblock#57]
>Imported CSS 

![Image](https://github.com/user-attachments/assets/815e500e-2623-4a8b-81d2-1f57dc6c165d)

>Nameplate still visible

![Image](https://github.com/user-attachments/assets/13b803ce-f159-4536-bd95-5993badca3b0)

**Comment by nixRidge** [comment]
Thanks. I still can't see nameplates on my end, but I'll play around with it a bit today to see if I can reproduce this.

**Comment by nixRidge** [comment]
I just updated the rule. Could you try this for me, please?

```css
/* Nameplate */
div[class^="member__"] > div[class*="nameplated__"] > div[class^="container__"]:has(div[class^="videoContainer__"]) {
  display: none;
}
```
